export const SET_USER_INITIAL_DATA = 'SET_USER_INITIAL_DATA';
export const SET_USER_PROFILE = 'SET_USER_PROFILE;';
export const SET_USER_ITEMS = 'SET_USER_ITEMS';

export const DELETE_USER_ENTRY = 'DELETE_USER_ENTRY';
